name: Build Buildroot Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check Nix flake
      run: nix flake check

    - name: Add AppArmor rule for bwrap using wildcard path (because Nix paths are silly)
      run: sudo cp .github/assets/apparmor/bwrap /etc/apparmor.d/bwrap && sudo systemctl reload apparmor

    - name: Cache Code
      uses: actions/cache@v4
      with:
        path: dl
        key: ${{ github.workflow }}-downloads-${{ hashFiles('configs/amtrak_midwest_test_defconfig') }}
        restore-keys:
          ${{ github.workflow }}-downloads-
    - name: Cache Compiled Code
      uses: actions/cache@v4
      with:
        path: |
          output/amtrak_midwest_test/build
        key: ${{ github.workflow }}-bin-${{runner.arch}}-${{ hashFiles('configs/amtrak_midwest_test_defconfig') }}
        restore-keys:
          ${{ github.workflow }}-bin-${{runner.arch}}-

    - name: Enter the nix develop shell
      uses: nicknovitski/nix-develop@v1.2.1

    - name: Setup environment and build
      run: source setup.sh && make
