name: Build Buildroot Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Disable AppArmor on the GitHub runner
      uses: cisagov/action-disable-apparmor@437d94f26a2e4bf8c03acfb500a6afc688b497db # v1.0.0
    
    - name: Enable non-priveleged user namespaces in kernel
      run: sudo sysctl -w kernel.unprivileged_userns_clone=1

    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check nix flake
      run: nix flake check

    - name: Build image
      run: nix develop --command make
